# Generated by Django 5.0.3 on 2024-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ticket_app', '0002_tbl_bustype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=25)),
            ],
        ),
    ]
