# Generated by Django 5.0.3 on 2024-03-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ticket_app', '0003_tbl_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=25, verbose_name='Bus No')),
                ('Source', models.CharField(max_length=25, verbose_name='Bus Starting Point')),
                ('Destination', models.CharField(max_length=25, verbose_name='Bus Ending Point')),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('bus_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_ticket_app.tbl_bustype')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_ticket_app.tbl_schedule')),
            ],
        ),
    ]
