# Generated by Django 5.0.3 on 2024-03-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ticket_app', '0004_tbl_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_bus',
        ),
    ]
