# Generated by Django 5.0.3 on 2024-03-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ticket_app', '0010_alter_tbl_bus_bus_type_id_alter_tbl_bus_schedule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_charge', models.IntegerField()),
                ('bus_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_ticket_app.tbl_bustype')),
            ],
        ),
    ]
