# Generated by Django 5.0.3 on 2024-03-30 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_ticket_app', '0015_tbl_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_smartcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_prize', models.IntegerField(verbose_name='Card Prize')),
                ('valid_from', models.DateField(verbose_name='Card Valid from')),
                ('valid_to', models.DateField(verbose_name='Card Valid To')),
                ('district', models.CharField(max_length=25, verbose_name='Card_valid_district')),
                ('payment_status', models.IntegerField(verbose_name='Card Fee Payment')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
